# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2020-06-19 19:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20200619_0354'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='billing_addr',
            new_name='billing_address',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='shipping_addr',
            new_name='shipping_address',
        ),
    ]
